### ISSUE TITLE
Disable profile page if profile chain is not loaded

### ISSUE THREAD

**Issue by nicholeous** [interbit/interbit#114]
Before the private account/identity chain has been loaded in the accounts page, the profile account page should not be available.

Disable based on chain status and github authentication status within the chain.

**Comment by karikushi** [comment]
The block explorer and chains pages should also be inaccessible if the user is not "signed in". We'll redirect to the Create Account / Sign In page if these pages are requested before chain load and github auth.

**Comment by djlmills** [comment]
@karikushi We may need to reconsider where block explorer and chains pages redirect to.

**Comment by karikushi** [comment]
@djlmills We can redirect each page to any component, so this is easy to do.

**Comment by karikushi** [comment]
Marking this as closed since we did the following:
- for all pages, show a loading page with no nav until the private chain is loaded
- if user's private chain does not have GitHub profile info, navigating to the Account Profile, Block Explorer, and Interactive Chains pages redirects to the Create Account page

We can make Block Explorer and Interactive Chains accessible to non-oAuthed users if we choose to do so.
