### ISSUE TITLE
move to hashes of pubkeys for all ACL checks

### ISSUE THREAD

**Issue by furiousOyster** [interbit/interbit#190]
much cleaner to deal with than storing the actual public key.
should use this for all proposal checks.
basically anywhere that a public key is checked by using a string comparison, we should use the hash.

**Comment by pekeler** [comment]
Yes, OpenPGP uses the "armored" encoding by default, so that info can survive a transfer via email. For us, the ASCII-armored encoding makes no sense and we should turn it off, i.e. store keypairs as hex-strings. If we did this, do you still think it's necessary to use hash values of keys in the ACL?

**Comment by brentbenton** [comment]
Migrated to new Core coordination process.
