### ISSUE TITLE
`assets` folder missing from interbit-ui-components

### ISSUE THREAD

**Issue by jared-dykstra** [interbit/interbit#701]
The assets folder is missing:
```
jared@Jared-Y50 MINGW64 /c/github/helixapps/test
$ git clone git@github.com:interbit/interbit.git
Cloning into 'interbit'...
remote: Counting objects: 15154, done.
remote: Compressing objects: 100% (150/150), done.
remote: Total 15154 (delta 144), reused 153 (delta 94), pack-reused 14910
Receiving objects: 100% (15154/15154), 45.08 MiB | 8.22 MiB/s, done.
Resolving deltas: 100% (10891/10891), done.

jared@Jared-Y50 MINGW64 /c/github/helixapps/test
$ cp -Rd interbit/packages/interbit-template .

jared@Jared-Y50 MINGW64 /c/github/helixapps/test
$ cd interbit-template/

jared@Jared-Y50 MINGW64 /c/github/helixapps/test/interbit-template
$ npm i

[...snip]

jared@Jared-Y50 MINGW64 /c/github/helixapps/test/interbit-template
$ npm run build

> interbit-template@0.4.48 build C:\github\helixapps\test\interbit-template
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '../assets/icons/reset.svg' in 'C:\github\helixapps\test\interbit-template\node_modules\interbit-ui-components\src\css'
```

**Comment by jared-dykstra** [comment]
Because this folder is only missing from the NPM bundle, a workaround is to copy the folder directly:

`cp -Rd ./packages/interbit-ui-components/src/assets ./node_modules/interbit-ui-components/src`

**Comment by jared-dykstra** [comment]
Related to #697, in that the steps described in this issue are essentially "getting started" steps  (@btlewan)

**Comment by nicholeous** [comment]
@jared-dykstra Building the template app is not required for the development work-flow. 

Copying the template out of the scope of the packages directory is not part of the getting started guide, (however this is clearly still a bug and will be addressed).

To work in development mode with the template outside of the scope of the packages directory, skip the build step and continue from step 2 on the [create your first Interbit application page](https://docs.interbit.io/getting-started/create.html).

Note that this will result in the error you have shown being displayed as a compile time error on the webapp until this issue is resolved.

We've also added another issue that will hopefully catch these issues in an integration test in the future. #702

**Comment by karikushi** [comment]
@jared-dykstra The error you're getting is caused by a combination of an incorrect webpack configuration in `interbit-ui-components` and the compiled CSS not referencing the correct url for the svg asset. The CSS shouldn't have a direct path to the asset, instead it should have a base64 encoded version. I'll post a comment here when this is fixed. 

Thanks also for discovering that the assets folder wasn't being copied correctly.

**Comment by jared-dykstra** [comment]
Thanks.  I've got my workaround for now, but will happily remove it when a fix is available.  (no rush)
